SELECT 
	CUST_ID,
	SNAP_DT,
	COUNT(DISTINCT if(trim(ACCT_TYPE_CD) IN ('CHQ', 'SAV'), ACCT_ID, Null)) AS NUM_ACCTS_DEB,
	COUNT(DISTINCT if(trim(ACCT_TYPE_CD) NOT IN ('CHQ', 'SAV'), ACCT_ID, Null)) AS NUM_ACCTS_CRE,
	SUM(if(trim(ACCT_TYPE_CD) IN ('CHQ', 'SAV'), END_BAL, 0)) AS END_BAL_DEB,
	SUM(if(trim(ACCT_TYPE_CD) NOT IN ('CHQ', 'SAV'), END_BAL, 0)) AS END_BAL_CRE,
	SUM(if(trim(ACCT_TYPE_CD) IN ('CHQ', 'SAV'), DR_AMT, 0)) AS DR_AMT_DEB,
	SUM(if(trim(ACCT_TYPE_CD) NOT IN ('CHQ', 'SAV'), DR_AMT, 0)) AS DR_AMT_CRE,
	SUM(if(trim(ACCT_TYPE_CD) IN ('CHQ', 'SAV'), CR_AMT, 0)) AS CR_AMT_DEB,
	SUM(if(trim(ACCT_TYPE_CD) NOT IN ('CHQ', 'SAV'), CR_AMT, 0)) AS CR_AMT_CRE,
	SUM(if(trim(ACCT_TYPE_CD) NOT IN ('CHQ', 'SAV'), CR_LMT, 0)) AS CR_LMT
FROM
	RAW.ACCOUNT
WHERE
	SNAP_DT = toDate32('{snap_dt}')
GROUP BY
	CUST_ID,
	SNAP_DT