WITH
	toDate32('{snap_dt}') AS SPDT
SELECT 
	CUST_ID,
	'{snap_dt}' AS SNAP_DT,
	date_diff('day', MAX(EVENT_TS), SPDT) AS DAYS_SINCE_LAST_EVENT,
	COUNT(EVENT_TS) AS NUM_EVENT_7D,
	SUM(IF(trim(EVENT_CHANNEL) = 'E', 1, 0)) / NUM_EVENT_7D AS RATIO_EVENT_EMAIL,
	SUM(IF(trim(EVENT_CD) = 'C', 1, 0)) / NUM_EVENT_7D AS RATIO_EVENT_CLICK,
	SUM(IF(trim(EVENT_CD) = 'D', 1, 0)) / NUM_EVENT_7D AS RATIO_EVENT_DECLINE
FROM
	RAW.EVENTS
WHERE
	EVENT_TS BETWEEN date_sub(DAY, 7, SPDT) AND SPDT
GROUP BY
	CUST_ID