WITH
CUST_BASE AS (
	SELECT * 
	FROM FEATURE.CUST_BASE
	WHERE SNAP_DT = toDate32('{snap_dt}')
),
ACCT_WINDOW AS (
	SELECT * 
	FROM FEATURE.ACCT_WINDOW
	WHERE SNAP_DT = toDate32('{snap_dt}')
),
EVENT_WINDOW AS (
	SELECT * 
	FROM FEATURE.EVENT_WINDOW
	WHERE SNAP_DT = toDate32('{snap_dt}')
)
SELECT
	C.CUST_ID AS CUST_ID,
	C.SNAP_DT AS SNAP_DT,
	-- customer feature
	GENDER,
	EMAIL_DOMAIN,
	BLOOD_GRP,
	SUPER_CITY,
	COASTAL_CITY,
	MANAGER_FLG,
	TECHNICAL_FLG,
	AGE,
	TENURE,
	TOTAL_COMP,
	BONUS_RATIO,
	-- account feature
	MAX_NUM_ACCT_7D,
	TOTAL_FLOW_7D,
	DEB_CRE_FLOW_7D,
	AVG_CR_UTIL_7D,
	MAX_CR_UTIL_7D,
	AVG_DR_DEB_3D,
	AVG_CR_DEB_3D,
	AVG_DR_CRE_3D,
	AVG_CR_CRE_3D,
	-- event feature
	ifNull(DAYS_SINCE_LAST_EVENT, 90) AS DAYS_SINCE_LAST_EVENT,
	ifNull(NUM_EVENT_7D, 0) AS NUM_EVENT_7D,
	RATIO_EVENT_EMAIL, -- allow null
	RATIO_EVENT_CLICK, -- allow null
	RATIO_EVENT_DECLINE -- allow null
FROM
	CUST_BASE AS C
	LEFT JOIN ACCT_WINDOW AS A ON
		C.CUST_ID = A.CUST_ID
		AND C.SNAP_DT = A.SNAP_DT 
	LEFT JOIN EVENT_WINDOW AS E ON
		C.CUST_ID = E.CUST_ID
		AND C.SNAP_DT = E.SNAP_DT
SETTINGS join_use_nulls = 1