version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - 9001:9000
      - 8123:8123
    volumes:
      - ${CH_VOLUME_MAPPING:-./docker-volume-mapping/clickhouse}:/var/lib/clickhouse:z
      #- ${CH_STATIC_FOLDER:-./docker-volume-mapping/clickhouse/user_files}:/var/lib/clickhouse/user_files:z
      - ${CH_CONFIG_FOLDER:-./configs/clickhouse}/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${CH_CONFIG_FOLDER:-./configs/clickhouse}/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${CH_CONFIG_FOLDER:-./configs/clickhouse}/obj_storage.xml:/etc/clickhouse-server/config.d/obj_storage.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: |
        wget --no-verbose --tries=1 --spider http://localhost:8123 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ${MONGO_VOLUME_MAPPING:-./docker-volume-mapping/mongodb}:/data  # the below volumes part
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    healthcheck:
      test: |
        echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 60s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb