name: test deployment
on:
  push:
    branches:
      - 'main'
    paths:
      - ".github/workflows/test-deploy.yml"

jobs:
  deploy:
    runs-on: luntaixia-ubuntu # need self hosted runner as need connect to local servers
    steps:
      - uses: actions/checkout@v4

      - name: read model version tag
        id: ver_tag
        uses: jbutcher5/read-yaml@main  # read yaml prebuilt action
        with:
          file: './fake-data-generator/build.yml'
          key-path: '["metadata", "version-tag"]'

      - name: read dockerhub model name
        id: model_nm
        uses: jbutcher5/read-yaml@main  # read yaml prebuilt action
        with:
          file: './fake-data-generator/build.yml'
          key-path: '["metadata", "docker-image-name"]'

      - name: pull docker image on faker prod machine
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.model_nm.outputs.data }}
          TAG: ${{ steps.ver_tag.outputs.data }}
          NAS_SERVICE_PORT: 9876
        run: |
          echo "Sending to fake prod machine @${{ secrets.FAKER_HOST }}:$NAS_SERVICE_PORT"

          echo "trying to pull docker image: $IMAGE:$TAG"
          curl -X 'POST' 'http://${{ secrets.FAKER_HOST }}:$NAS_SERVICE_PORT/docker/image/pull' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"image_name": "$IMAGE", "tag": "$TAG"}' 